### ISSUE TITLE
Automatically launch Everything.exe if it's not already running

### ISSUE THREAD

**Issue by redactedscribe** [TheZoc/EverythingDopusCLI#6]
I currently use a shortcut (via AHK) to launch Everything.exe so it needn't be consuming 500 MB of RAM continuously. This script therefore won't work. Indeed, your README says Everything needs to be running in the background, but it would be cool if it could launch it if it isn't. The only thing running for me is the Everything.exe as a service which takes ~3 MB of RAM.

**Comment by redactedscribe** [comment]
@TheZoc Something I just came across is Everything being natively supported in Directory Opus 13 which may be of interest to you in case you aren't aware: https://docs.dopus.com/doku.php?id=release_history:opus13:page1#everything_indexed_search

**Comment by TheZoc** [comment]
@redactedscribe Whoa there's a lot to unpack here!

> I currently use a shortcut (via AHK) to launch Everything.exe so it needn't be consuming 500 MB of RAM continuously. This script therefore won't work.

Great! Sounds like you got your workflow sorted already! :)

> Indeed, your README says Everything needs to be running in the background, but it would be cool if it could launch it if it isn't.

The focus of this application is speed, ease of use and command line support. There are no plans to launch Everything if it isn't already running - that would only add an unnecessary delay for an edge case that all of the current users don't care about.

> The only thing running for me is the Everything.exe as a service which takes ~3 MB of RAM.

Good for you :)

> Something I just came across is Everything being natively supported in Directory Opus 13 which may be of interest to you in case you aren't aware

I am aware, thank you - I've been using the beta since the first public release.
However, it needs Everything to be running in the background for it to work - it might not be an useful addition for you.

Keep in mind that the integration does not support the creation of collections based on results and does not support command line input. If you don't require those, it's a great tool to use, provided you keep Everything running on the background.

I hope to have answered your remarks in an useful way - I'll close this issue. Feel free to open a new issue if you have a request or a bug report that I might be able to help with.
